language: node_js
node_js: node

os: linux
arch: amd64
dist: focal

cache:
  apt: true
  yarn: true

branches: main

addons:
  apt:
    update: true

git:
  strategy: clone
  quiet: true
  autocrlf: input
  depth: false
  symlinks: true

script:
  - yarn build

deploy:
  strategy: git
  provider: pages
  edge: true
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: main
